### ISSUE TITLE
All stop feature

### ISSUE THREAD

**Issue by pleonber** [kloon/OpenBeerFiller#1]
I recommend implementing a "all stop" feature.   This would be a button (you can use the start button for this) to stop machine at any point.

Based on earlier concepts I designed a state machine which will allow the can filler to stop from any state.   I'll attached the code here for reference purposes.

[can_filler_state_maching_example.txt](https://github.com/kloon/OpenBeerFiller/files/4537195/can_filler_state_maching_example.txt)

**Comment by BaggyLala** [comment]
Thanks for the input "All stop" feature is now considered within the code. An additional button will be added to the build that is attached to the controllers reset pin. This way any power interruptions will also set the machine back to a known state with all the valves shut etc.
In the event of any major reworking of this code being required we will certainly look again at the approach used in your example text file.
